### ISSUE TITLE
Could not customize maven repositories

### ISSUE THREAD

**Issue by todoubaba** [dsyer/spring-boot-thin-launcher#33]
[mavenRepositories](https://github.com/dsyer/spring-boot-thin-launcher/blob/master/launcher/src/main/java/org/springframework/boot/loader/thin/DependencyResolver.java#L287) fixes maven repositories to `local`, `spring-snapshots` and `central`, I could not find a way to add a new one.

The scenario is that I test spring-boot-thin in a grails project whose default repo is `https://repo.grails.org/grails/core`, some jars only published to that repo. When running the thin-jar, it reports the following exception:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:112)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:81)
Caused by: java.lang.RuntimeException: Could not find artifact org.grails:grails-gsp:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-gsp:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-web-gsp:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-web-gsp:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-web-sitemesh:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-web-sitemesh:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:converters:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:converters:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:cache:jar:4.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:cache:jar:4.0.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:hibernate5:jar:6.1.6 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:hibernate5:jar:6.1.6 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:gsp:jar:3.3.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:gsp:jar:3.3.0 in central (https://repo1.maven.org/maven2)
Could not find artifact com.bertramlabs.plugins:asset-pipeline-grails:jar:2.14.2 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact com.bertramlabs.plugins:asset-pipeline-grails:jar:2.14.2 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-gorm-testing-support:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-gorm-testing-support:jar:1.0.0 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails.plugins:geb:jar:1.1.1 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails.plugins:geb:jar:1.1.1 in central (https://repo1.maven.org/maven2)
Could not find artifact org.grails:grails-web-testing-support:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact org.grails:grails-web-testing-support:jar:1.0.0 in central (https://repo1.maven.org/maven2)
        at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:205)
        at org.springframework.boot.loader.thin.PathResolver.extract(PathResolver.java:182)
        at org.springframework.boot.loader.thin.PathResolver.resolve(PathResolver.java:94)
        at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:324)
        at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:186)
        at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:139)
```

I think thin-jar should follow the `build.gradle`'s `repositories`.

**Comment by dsyer** [comment]
You have to put the extra repositories in the generated pom (or in your settings.xml). There;s probably a Gradle way to do that, and it's not really a thin jat thing, I think.

**Comment by todoubaba** [comment]
Yeah, using `mirror` in settings.xml works, thanks.
