### ISSUE TITLE
Running build fails at simple

### ISSUE THREAD

**Issue by aliostad** [dsyer/spring-boot-thin-launcher#5]
Running build fails at simple:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] tools .............................................. SUCCESS [  4.051 s]
[INFO] Thin Launcher ...................................... SUCCESS [  2.282 s]
[INFO] maven-plugin ....................................... SUCCESS [  4.943 s]
[INFO] Thin Wrapper ....................................... SUCCESS [  0.865 s]
[INFO] Thin Launcher Parent ............................... SUCCESS [  0.073 s]
[INFO] Thin Launcher Gradle ............................... SUCCESS [  0.744 s]
[INFO] capsule-app ........................................ SUCCESS [  8.304 s]
[INFO] app ................................................ SUCCESS [  5.719 s]
[INFO] simple ............................................. FAILURE [  7.676 s]
[INFO] Thin Launcher Samples .............................. SKIPPED
[INFO] Thin Launcher Sample Tests ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.774 s
[INFO] Finished at: 2017-01-19T22:11:08+00:00
[INFO] Final Memory: 99M/668M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot.experimental:spring-boot-thin-maven-plugin:0.0.1.BUILD-SNAPSHOT:resolve (resolve) on project simple: Cannot locate deployable /Users/aliostad/github/spring-boot-thin-launcher/samples/simple/target/simple-0.0.1-SNAPSHOT.jar: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

And the error seems to be

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:92)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:77)
Caused by: org.springframework.boot.cli.compiler.grape.DependencyResolutionFailedException: java.lang.IllegalStateException: Cannot resolve version for org.springframework.cloud:spring-cloud-starter-config:jar: ()
	at org.springframework.boot.loader.thin.AetherEngine.resolveDependencies(AetherEngine.java:236)
	at org.springframework.boot.loader.thin.AetherEngine.resolveTransitive(AetherEngine.java:245)
	at org.springframework.boot.loader.thin.AetherEngine.resolve(AetherEngine.java:186)
	at org.springframework.boot.loader.thin.ArchiveUtils$ArchiveDependencies.resolve(ArchiveUtils.java:411)
	at org.springframework.boot.loader.thin.ArchiveUtils.extract(ArchiveUtils.java:264)
	at org.springframework.boot.loader.thin.ArchiveUtils.combine(ArchiveUtils.java:709)
	at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:245)
	at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:139)
	at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:102)
	... 6 more
Caused by: java.lang.IllegalStateException: Cannot resolve version for org.springframework.cloud:spring-cloud-starter-config:jar: ()
	at org.springframework.boot.loader.thin.AetherEngine.getCollectRequest(AetherEngine.java:298)
	at org.springframework.boot.loader.thin.AetherEngine.resolveDependencies(AetherEngine.java:228)
```

**Comment by dsyer** [comment]
Works for me now (and that code was replaced, so probably worth another try). Also there are snapshots (and 2 milestone) releases in repo.spring.io: http://repo.spring.io/libs-snapshot/org/springframework/boot/experimental/.
