### ISSUE TITLE
Application run failed due by java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by alexfdezsauco** [dsyer/spring-boot-thin-launcher#61]
`java -jar file.jar `

After a successful build I'm tried to run the application and failed due by a `java.lang.NoSuchMethodError` exception.

Details:

```
 ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: org.springframework.util.Assert.isTrue(ZLjava/util/function/Supplier;)V
        at org.springframework.boot.context.properties.bind.Bindable.withExistingValue(Bindable.java:162)
        at org.springframework.boot.context.properties.bind.Bindable.ofInstance(Bindable.java:192)
        at org.springframework.boot.SpringApplication.bindToSpringApplication(SpringApplication.java:548)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
        at ensemble.jobs.aetfromlstml.Application.main(Application.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:192)
        at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:139)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:126)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:98)

```

**Comment by dsyer** [comment]
Looks like maybe you compiled with a different version of Spring Boot than you used at runtime, and they are not compatible. If you can provide a sample project that someone can run to reproduce this error it will be easier to say.

**Comment by alexfdezsauco** [comment]
Thanks, exactly.
