### ISSUE TITLE
ClassNotFoundException with thin jar when project configures logback natively (not via Spring Boot)

### ISSUE THREAD

**Issue by lucpolak** [dsyer/spring-boot-thin-launcher#68]
Hello,
I have a project using logback as logger.
In the POM I have a dependency to ch.qos.logback core and api.

When building a thin jar, the ch.qos classes are relocated to hidden.ch.qos and this causes this Exception.

> 11:27:44,624 |-ERROR in hidden.ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [ch.qos.logback.core.rolling.RollingFileAppender]. hidden.ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.rolling.RollingFileAppender
	at hidden.ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.rolling.RollingFileAppender
	at 	at hidden.ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at hidden.ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at hidden.ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at hidden.ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	at hidden.ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at hidden.ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at hidden.ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at hidden.ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at hidden.ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at hidden.ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at hidden.ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at hidden.ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at hidden.ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at hidden.ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at hidden.org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at hidden.org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at hidden.org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at hidden.org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at hidden.org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at hidden.org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at hidden.org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at org.springframework.boot.loader.thin.ThinJarLauncher.<clinit>(ThinJarLauncher.java:49)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:140)
	at 	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.rolling.RollingFileAppender
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at hidden.ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)

I've found that in the spring-boot-thin-launcher POM.XML, you relocate these classes to hidden.*

Can I override these settings in my POM to be sure that will work ? 

Thank you for support ;-)

Regards

**Comment by dsyer** [comment]
You shouldn't be using the poms from this project for anything. Just the binaries. Look at the samples for copy-paste code.

**Comment by lucpolak** [comment]
Hey @dsyer,
Thank you for answer.
I don't use this pom. I've just cloned the repo to try to understand why the ch.qos classes are relocated and I found these relocations in this pom.

Here you can find my project's pom : 

>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.17.RELEASE</version>
        <relativePath/> 
    </parent>

    <properties>
        <slf4j.version>1.7.25</slf4j.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <compiler.version>3.3</compiler.version>
        <maven.rpm.version>2018.10.05</maven.rpm.version>
        <maven.rpm.release>02</maven.rpm.release>
        <maven.rpm.phase>package</maven.rpm.phase>
        <app.version>${maven.rpm.version}.${maven.rpm.release}</app.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <springfox.version>2.9.2</springfox.version>
        <start-class>com.oxit.rfid.retail.OVHCollector</start-class>
    </properties>

    <groupId>com.oxit.rfid.retail</groupId>
    <artifactId>dkt-overhead-collector</artifactId>
    <version>${app.version}</version>

    <dependencies>
        
    </dependencies>

    <build>
        
        
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.springframework.boot.experimental</groupId>
                        <artifactId>spring-boot-thin-layout</artifactId>
                        <version>1.0.17.RELEASE</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>


If you think that something is wrong, let me know ;-)

**Comment by dsyer** [comment]
I can't see anything wrong with that. Can you put the whole project (or just a minimal one showing the problem) in github please?

**Comment by lucpolak** [comment]
I will try to create a minimalist test projets ASAP.

**Comment by dsyer** [comment]
I'll see if I can fix that. Maybe we don't need logback here anyway.

**Comment by dsyer** [comment]
This should be fixed in 7b8e651 (we don't need logback on startup really).
