### ISSUE TITLE
Run with exception

### ISSUE THREAD

**Issue by rickywu** [dsyer/spring-boot-thin-launcher#73]
I use gradle thinResolve build OK and run with
java -Dthin.root=. -jar sample.jar

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:140)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/MultipartConfigElement
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:193)
        at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:140)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.MultipartConfigElement
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
        at org.springframework.boot.loader.thin.ThinJarLauncher$ThinJarClassLoader.loadClass(ThinJarLauncher.java:459)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
```

my build.gradle is 

```
buildscript {
	ext {
		springBootVersion = '2.0.0.RELEASE'
		wrapperVersion = '1.0.17.RELEASE'
	}
	repositories {
        mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot.experimental:spring-boot-thin-gradle-plugin:${wrapperVersion}")
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'org.springframework.boot'
apply plugin: "io.spring.dependency-management"
apply plugin: 'org.springframework.boot.experimental.thin-launcher'

group = 'com.dcmd.service.demand'
version = '1.0.0-SNAPSHOT'

sourceCompatibility = 1.8
targetCompatibility = 1.8
tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}

thinResolvePrepare {
	into new File("${buildDir}/thin/deploy")
}

repositories {
             mavenCentral()
}

configurations { compile.exclude module: 'spring-boot-starter-tomcat' }

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Finchley.RELEASE'
    }
}

dependencies {
    compile group: 'com.company.common.core', name: 'company-common', version:'1.0.0-SNAPSHOT', changing: true
}
```

**Comment by rickywu** [comment]
I found the reason is this line
compile group: 'com.company.common.core', name: 'company-common', version:'1.0.0-SNAPSHOT', changing: true

Remove it then the spring boot application can startup.

com.company.common.core this package is one parent spring cloud dependencies package:

```
dependencies {
    compile group: 'javax.servlet', name: 'javax.servlet-api', version:'3.1.0'
    compile group: 'com.jayway.jsonpath', name: 'json-path', version:'2.4.0'
    compile group: 'org.hibernate.validator', name: 'hibernate-validator', version:'6.0.7.Final'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-netflix-eureka-client', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-config', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-openfeign', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-netflix-hystrix', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-netflix-hystrix-dashboard', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-zipkin', version:'2.0.0.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-sleuth', version:'2.0.0.RELEASE'
    compile group: 'io.springfox', name: 'springfox-swagger2', version:'2.8.0'
    compile group: 'io.springfox', name: 'springfox-swagger-ui', version:'2.8.0'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-batch', version:'2.0.0.RELEASE'
    compile group: 'com.alibaba', name: 'fastjson', version:'1.1.41'
    compile group: 'com.alibaba', name: 'druid', version:'1.1.9'
    compile group: 'org.springframework', name: 'spring-tx', version:'5.0.4.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-jdbc', version:'2.0.0.RELEASE'
    compile group: 'mysql', name: 'mysql-connector-java', version:'5.1.45'
    compile group: 'org.mybatis.spring.boot', name: 'mybatis-spring-boot-starter', version:'1.1.1'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-redis', version:'2.0.0.RELEASE'
    compile group: 'commons-lang', name: 'commons-lang', version:'2.6'
    compile group: 'org.apache.commons', name: 'commons-lang3', version:'3.1'
    compile group: 'log4j', name: 'log4j', version:'1.2.17'
    compile group: 'org.apache.poi', name: 'poi-ooxml', version:'3.15'
    compile group: 'redis.clients', name: 'jedis', version:'2.8.2'
    compile group: 'commons-net', name: 'commons-net', version:'3.3'
    compile group: 'net.oschina.zcx7878', name: 'fastdfs-client-java', version:'1.27.0.0'
    compile group: 'io.jsonwebtoken', name: 'jjwt', version:'0.9.0'
    testCompile group: 'org.springframework.boot', name: 'spring-boot-starter-test', version:'2.0.0.RELEASE'
    compileOnly group: 'org.projectlombok', name: 'lombok', version:'1.16.20'
}
```

**Comment by rickywu** [comment]
Try this sample to reproduce https://github.com/rickywu/thin-gradle

You need change repo url to build dcmd-common-parent first and use as dependency.

**Comment by dsyer** [comment]
I don't really understand how to build this project. Can you modify it to build and install locally?

**Comment by dsyer** [comment]
I can build the library and the app from master, and then run the app. It fails because it can't find a database, but it runs fine. What am I looking for?

**Comment by rickywu** [comment]
I found the problem is my build.gradle removed this lien: 
    apply plugin: 'io.spring.dependency-management'
that caused thinResolve task not download dependencies

Another problem is thinResolve not use gradle caches but use maven local repo, how can I use gradle caches?

**Comment by dsyer** [comment]
I don't know. What is a "gradle cache"? Is that related to #50? For the best results you need to use the maven local cache I think so that you actually generate a `pom.xml`, but if you are a gradle expert you might know a better way. Please open another issue if you have any ideas (PR more than welcome).
